title:        Saglac IO
tagline:      "saglac.io"
description:  "Le Saglac IO se veut un événement informel entre passionnés de technologies."
url:          http://saglac.io
email:        info@saglac.io
markdown:     redcarpet
permalink:    pretty
highlighter:  rouge
paginate:     5
# plugins: [jekyll-paginate]
sass:
  sass_dir: _sass

facebook_app_id: 130024877754864
facebook_default_image: /images/open-graph-default-image.png
